// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107145223_newnew")]
    partial class newnew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mood")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "I had an amazing day at my graduation party.",
                            Mood = 0,
                            Title = "Graduation Day"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 1, 25, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "I was nervous but I think it went well!",
                            Mood = 4,
                            Title = "First Job Interview"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spent a relaxing week at the beach with friends.",
                            Mood = 0,
                            Title = "Vacation Time"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2025, 2, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Excited to start building apps with C# and ASP.NET Core.",
                            Mood = 2,
                            Title = "Started Learning C#"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2025, 3, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Completed my first small console app today!",
                            Mood = 5,
                            Title = "First Coding Project"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2025, 3, 5, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "It rained all day, stayed indoors and read a book.",
                            Mood = 3,
                            Title = "Rainy Day"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2025, 3, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Had an amazing workout, feeling strong and healthy.",
                            Mood = 2,
                            Title = "Gym Motivation"
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2025, 3, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Met an old friend for coffee, great conversation.",
                            Mood = 0,
                            Title = "Coffee with Friend"
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2025, 3, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Practiced guitar for 2 hours, learning a new song.",
                            Mood = 3,
                            Title = "Learning Guitar"
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2025, 3, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Watched a classic movie and enjoyed every minute.",
                            Mood = 0,
                            Title = "Movie Night"
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2025, 3, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Went hiking in the mountains, breathtaking views.",
                            Mood = 2,
                            Title = "Hiking Trip"
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2025, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tried a new recipe today, turned out delicious.",
                            Mood = 5,
                            Title = "Cooking Experiment"
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2025, 4, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Helped at a local shelter, felt very fulfilling.",
                            Mood = 5,
                            Title = "Volunteer Work"
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2025, 4, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Solved a tricky coding problem, very proud!",
                            Mood = 2,
                            Title = "Coding Challenge"
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2025, 4, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spent the day relaxing, reading, and enjoying music.",
                            Mood = 3,
                            Title = "Relaxing Sunday"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
